//Sobreescribo los slide del asistente ya que cambia para este flavor
slides_asistente = [
    {"id": "slide_firmar_acta",
     "template": "slides/firmar_acta",
     "context_tiles": ["panel_estado", "panel_asistente", "panel_finalizar"],
    },
    {"id": "slide_certificados_extra",
     "template": "slides/certificados_extra",
     "context_tiles": ["panel_estado", "panel_asistente", "panel_finalizar"],
    },
    {"id": "slide_paso_1",
     "template": "escrutinio/slides/paso_1",
     "context_tiles": ["panel_estado", "panel_asistente", "panel_finalizar"],
    },
    {"id": "slide_paso_2",
     "template": "escrutinio/slides/paso_2",
     "context_tiles": ["panel_estado", "panel_asistente", "panel_finalizar"],
    },
    {"id": "slide_paso_3",
     "template": "escrutinio/slides/paso_3",
     "context_tiles": ["panel_estado", "panel_asistente", "panel_finalizar"],
    },
    {"id": "slide_paso_4",
     "template": "escrutinio/slides/paso_4",
     "context_tiles": ["panel_estado", "panel_asistente", "panel_finalizar"],
    },
    {"id": "slide_paso_5",
     "template": "escrutinio/slides/paso_5",
     "context_tiles": ["panel_estado", "panel_asistente", "panel_finalizar"],
    },
    {"id": "slide_paso_6",
     "template": "escrutinio/slides/paso_6",
     "context_tiles": ["panel_estado", "panel_asistente", "panel_finalizar"],
    },
    {"id": "slide_paso_7",
     "template": "escrutinio/slides/paso_7",
     "context_tiles": ["panel_estado", "panel_asistente", "panel_finalizar"],
    },
    {"id": "slide_paso_8",
        "template": "escrutinio/slides/paso_8",
        "context_tiles": ["panel_estado", "panel_asistente", "panel_finalizar"],
    },
    {"id": "slide_qr_fiscales",
     "template": "slides/qr_fiscales",
     "context_tiles": ["panel_estado", "panel_asistente", "panel_finalizar"],
    }
];