
CIERRE_RECUENTO = 'recuento'
CIERRE_TRANSMISION = 'transmision'
CIERRE_CERTIFICADO = 'certificado'
CIERRE_COPIA_FIEL = 'copia_fiel'
CIERRE_ESCRUTINIO = 'escrutinio'
CIERRE_TACHAS = 'tachas'
CIERRE_PREFERENCIAS = 'preferencias'

CREDENCIAL_AUTORIDAD = 'autoridad'
CREDENCIAL_TECNICO = 'tecnico'
CREDENCIAL_DEMOSTRACION = 'demostracion'

BITS_DNI = 27

LEN_LEN_UBIC = 2
LEN_LEN_OPC = 3
LEN_LEN_PRE = 3
LEN_LEN_TAC = 3

